### ISSUE TITLE
tag case_result

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/cz-supreme-court-crawler#1]
neutral:

- if _část rozhodnutí po slovu "takto" (výrok rozhodnutí)_ contains "zastavuje"  & not contains "zrušuje" | "zamítá" | "odmítá"

positive

- if "Typ rozhodnutí" == "ROZSUDEK"

- if "Spisová značka" obsahuje "Tdo" & _část rozhodnutí po slovu "takto" (výrok rozhodnutí)_ contains "zrušuje" | "zamítá" & not contains "zastavuje" | "odmítá"

negative

-  if _část rozhodnutí po slovu "takto" (výrok rozhodnutí)_ contains "odmítá" & not contains "zrušuje" | "zamítá" | "zastavuje"

unknown

- if _část rozhodnutí po slovu "takto" (výrok rozhodnutí)_ contains more from word-list "odmítá" | "zrušuje" | "zamítá" | "zastavuje" at the same time

**Comment by repli2dev** [comment]
Nepatří ke crawleru, ale značkovači. Momentálně takto (či velmi podobně) implementováno, takže zavírám.
