### ISSUE TITLE
get advocates' name from decision

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/cz-supreme-court-crawler#2]
- u věcí "Tdo" tam advokáta, zdá se, nikdy nepíšou -> proto jsme je vyřadili ze stahování
- u ostatních vysvětlím raději česky a na příkladu

"Nejvyšší soud České republiky rozhodl v senátě složeném z předsedy JUDr. Zdeňka Krčmáře a soudců JUDr. Petra Hampla a JUDr. Ivany Štenglové v právní věci žalobkyně K., s. r. o., zastoupené JUDr. V. K., advokátem, **2 proti žalované** K. D., a. s., **3 zastoupené JUDr. Alešem Pejchalem, advokátem**, o zaplacení částky 380.156,20 Kč s příslušenstvím, vedené u Krajského soudu v Českých Budějovicích pod sp. zn. 12 Cm 1096/97, **1 o dovolání žalované** proti rozsudku Vrchního soudu v Praze ze dne 21. září 2000, č. j. 1 Cmo 98/99 - 155, takto: "

1 podívám se, kdo podával dovolání
2 přejdu do relevantní části hlavičky (budˇ "v právní věci žalob*" nebo "proti žalovan*")
3 z označeného výrazu vytáhnu jméno a příjmení advokáta (a asi i titul, pro jednodušší prolinkování se seznamem z ČAKu)

**Comment by repli2dev** [comment]
Nepatří ke crawleru, ale značkovači. Momentálně takto (či velmi podobně) implementováno, takže zavírám.
