### ISSUE TITLE
upravit seznam stahovanych spisovek

### ISSUE THREAD

**Issue by tpapouskova** [datoszs/cz-supreme-court-crawler#6]
vyskrtnout "Tdo" (to uz jsi asi udelal)

vyskrtnout "Odon" a "Cdon" (jednak tam nikde nevidim vhodne napsany udaj o advokatovi, jednak tyto rejstriky stejne od roku 2001 zrusili a my patrne budeme garantovat uplnost informaci az od pozdejsiho data...)

pridat "NSCR" (od roku 2008)

**Comment by repli2dev** [comment]
Zatim takovy seznam neexistuje, nicmene se nadale budu zabyvat tedy jen CDO a NSCR.

**Comment by tpapouskova** [comment]
pro úplnost (si) shrnuji

- zpracováváme Cdo, NSČR
- ještě **prosím o přidání ICdo**
- Odo a Tdo nezpracováváme, protože si myslíme, že tam není uváděn údaj o advokátovi (bylo by to ale možná fajn **na vzorku ověřit**)
- Cdon, Odon nezpracováváme, protože v nich ve sledovaném období (od 1. 6. 2000) už nebylo nic rozhodováno
- ostatní rejstříky (viz [seznam](http://nsoud.cz/JudikaturaNS_new/ns_web.nsf/web/Napoveda~Vyhledavanirozhodnuti~Druhy_veci_projednavanych_Nejvyssim_soudem~?openDocument&lng=CZ)) nezpracováváme, protože nejsou relevantní - nejde o řízení o dovlání, v nichž je dovolatel povinně zastoupen advokátem (toto by ale bylo dobré prodiskutovat s někým ze soudu, abych si tím byla jistá...)

**Comment by repli2dev** [comment]
Hlásím, že v TDO opravdu nejsou. V ODO buď nejsou, anebo jsou anonymizované (J. B.)

**Comment by repli2dev** [comment]
Zavírám úkol, poněvadž toto bude implementováno v rámci hlavního projektu. Crawler je jen tupá utilita, které se předává seznam spisovek, které má použít.
